import type { CategoryId } from '../types'

/**
 * Keyword → category rules. Longer / more specific phrases are matched first.
 * Order within a category doesn't matter; we score by match length.
 */
const RULES: { category: CategoryId; keywords: string[] }[] = [
  {
    category: 'fruit-veg',
    keywords: [
      'apple',
      'apples',
      'banana',
      'bananas',
      'orange',
      'oranges',
      'lemon',
      'lemons',
      'lime',
      'limes',
      'grape',
      'grapes',
      'berry',
      'berries',
      'strawberry',
      'strawberries',
      'blueberry',
      'blueberries',
      'raspberry',
      'raspberries',
      'avocado',
      'avocados',
      'tomato',
      'tomatoes',
      'potato',
      'potatoes',
      'kumara',
      'sweet potato',
      'onion',
      'onions',
      'garlic',
      'carrot',
      'carrots',
      'broccoli',
      'cauliflower',
      'cabbage',
      'lettuce',
      'spinach',
      'kale',
      'celery',
      'cucumber',
      'zucchini',
      'courgette',
      'capsicum',
      'pepper',
      'peppers',
      'mushroom',
      'mushrooms',
      'corn',
      'peas',
      'beans',
      'green beans',
      'salad',
      'salad mix',
      'herbs',
      'coriander',
      'parsley',
      'basil',
      'mint',
      'ginger',
      'chilli',
      'chili',
      'mango',
      'mangoes',
      'pineapple',
      'watermelon',
      'melon',
      'kiwifruit',
      'kiwi',
      'pear',
      'pears',
      'peach',
      'peaches',
      'plum',
      'plums',
      'fruit',
      'veg',
      'vegetable',
      'vegetables',
      'produce',
    ],
  },
  {
    category: 'dairy',
    keywords: [
      'milk',
      'oat milk',
      'almond milk',
      'soy milk',
      'cream',
      'sour cream',
      'whipping cream',
      'butter',
      'margarine',
      'cheese',
      'cheddar',
      'mozzarella',
      'parmesan',
      'feta',
      'cream cheese',
      'yogurt',
      'yoghurt',
      'greek yogurt',
      'greek yoghurt',
      'custard',
      'dairy',
      'eggs',
      'egg',
      'creme',
      'crème',
    ],
  },
  {
    category: 'meat',
    keywords: [
      'chicken',
      'beef',
      'steak',
      'mince',
      'minced',
      'pork',
      'bacon',
      'ham',
      'sausage',
      'sausages',
      'lamb',
      'turkey',
      'duck',
      'fish',
      'salmon',
      'tuna',
      'cod',
      'prawn',
      'prawns',
      'shrimp',
      'seafood',
      'meat',
      'schnitzel',
      'chops',
      'ribs',
      'wings',
      'drumstick',
      'thigh',
      'breast',
    ],
  },
  {
    category: 'bakery',
    keywords: [
      'bread',
      'loaf',
      'bagel',
      'bagels',
      'bun',
      'buns',
      'roll',
      'rolls',
      'croissant',
      'croissants',
      'muffin',
      'muffins',
      'pastry',
      'pastries',
      'cake',
      'cakes',
      'cookie',
      'cookies',
      'biscuit',
      'biscuits',
      'cracker',
      'crackers',
      'tortilla',
      'wraps',
      'pita',
      'naan',
      'baguette',
      'sourdough',
      'bakery',
      'donut',
      'doughnut',
    ],
  },
  {
    category: 'freezer',
    keywords: [
      'frozen',
      'freezer',
      'ice cream',
      'icecream',
      'ice-cream',
      'gelato',
      'popsicle',
      'ice block',
      'iceblock',
      'frozen pizza',
      'frozen veg',
      'frozen vegetables',
      'frozen berries',
      'frozen chips',
      'hash brown',
      'hashbrowns',
      'nuggets',
      'fish fingers',
      'ice cubes',
    ],
  },
  {
    category: 'drinks',
    keywords: [
      'juice',
      'orange juice',
      'apple juice',
      'soda',
      'soft drink',
      'soft drinks',
      'coke',
      'cola',
      'pepsi',
      'sprite',
      'fanta',
      'lemonade',
      'water',
      'sparkling water',
      'mineral water',
      'beer',
      'wine',
      'cider',
      'coffee',
      'tea',
      'green tea',
      'energy drink',
      'smoothie',
      'cordial',
      'drink',
      'drinks',
      'beverage',
      'kombucha',
      'milkshake',
    ],
  },
  {
    category: 'household',
    keywords: [
      'toilet paper',
      'toilet roll',
      'paper towel',
      'paper towels',
      'tissues',
      'tissue',
      'soap',
      'hand soap',
      'dish soap',
      'dishwashing',
      'detergent',
      'laundry',
      'washing powder',
      'washing liquid',
      'fabric softener',
      'bleach',
      'cleaner',
      'cleaning',
      'disinfectant',
      'wipes',
      'bin bags',
      'bin liners',
      'garbage bags',
      'trash bags',
      'foil',
      'cling wrap',
      'glad wrap',
      'baking paper',
      'sponges',
      'sponge',
      'shampoo',
      'conditioner',
      'toothpaste',
      'toothbrush',
      'deodorant',
      'razor',
      'batteries',
      'light bulb',
      'lightbulbs',
      'household',
    ],
  },
  {
    category: 'pantry',
    keywords: [
      'rice',
      'pasta',
      'spaghetti',
      'noodles',
      'cereal',
      'oats',
      'oatmeal',
      'muesli',
      'flour',
      'sugar',
      'salt',
      'pepper',
      'oil',
      'olive oil',
      'vinegar',
      'sauce',
      'soy sauce',
      'tomato sauce',
      'ketchup',
      'mayo',
      'mayonnaise',
      'mustard',
      'jam',
      'honey',
      'peanut butter',
      'nutella',
      'spread',
      'canned',
      'tinned',
      'beans',
      'chickpeas',
      'lentils',
      'stock',
      'broth',
      'soup',
      'spice',
      'spices',
      'seasoning',
      'baking',
      'yeast',
      'chocolate',
      'chips',
      'crisps',
      'nuts',
      'almonds',
      'cashews',
      'snack',
      'snacks',
      'crackers',
      'tuna can',
      'canned tuna',
      'pantry',
      'granola',
      'cornflakes',
      'weetbix',
      'vegemite',
      'marmite',
    ],
  },
]

// Precompute sorted keywords (longest first) for better phrase matching
const FLAT: { keyword: string; category: CategoryId }[] = RULES.flatMap((r) =>
  r.keywords.map((keyword) => ({
    keyword: keyword.toLowerCase(),
    category: r.category,
  })),
).sort((a, b) => b.keyword.length - a.keyword.length)

/**
 * Infer a grocery category from free-text item name.
 * Returns `other` when nothing confident matches.
 */
export function detectCategoryFromName(name: string): CategoryId {
  const text = name.trim().toLowerCase()
  if (!text) return 'other'

  // Prefer whole-word / phrase matches; longest keyword wins
  for (const { keyword, category } of FLAT) {
    if (keyword.includes(' ')) {
      if (text.includes(keyword)) return category
      continue
    }
    // Word-boundary match so "ham" doesn't hit "shampoo" incorrectly...
    // but "shampoo" is household and longer keywords are checked first.
    const re = new RegExp(`(^|[^a-z])${escapeRegExp(keyword)}([^a-z]|$)`, 'i')
    if (re.test(text)) return category
  }

  return 'other'
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export function categoryLabel(id: CategoryId): string {
  const map: Record<CategoryId, string> = {
    'fruit-veg': 'Fruit & Veg',
    dairy: 'Dairy',
    meat: 'Meat',
    bakery: 'Bakery',
    pantry: 'Pantry',
    freezer: 'Freezer',
    drinks: 'Drinks',
    household: 'Household',
    other: 'Other',
  }
  return map[id] ?? 'Other'
}
